version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo installing dependencies...
      - npm install
      - npm install -g @angular/cli@12.0.0
      - npm audit fix --force
  build:
    commands:
      - echo Build started...
      - ng build

  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no
