/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://lkxlfivj2nccpb6ak7ydq5n6ci.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-b6zfo3rbwjhy3a6d46wujs2eme",
    "aws_cognito_identity_pool_id": "us-east-1:4f791e96-ce20-4cb0-89b1-c7856b5c88e8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dYQgwDAwi",
    "aws_user_pools_web_client_id": "6t01ohg478kqiukpasb4hlo97m",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "EMAIL"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
